server.port: 9003
tracer.property: I AM THE DEFAULT
spring.jpa.show-sql: true
spring.datasource.url: jdbc:mysql://localhost:3306/product_service
spring.datasource.username: root
spring.datasource.password: null
spring.datasource.testWhileIdle: true
spring.datasource.validationQuery: SELECT 1
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
